var sweety = 'sweety';
var cutie = 'cutie';
console.log("********** Before Swap *********");
console.log('');
console.log("1) sweety: ", sweety, "2)  cutie: ", cutie);
console.log('');
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log("********** After Swap **********");
console.log('');
console.log("1) sweety: ", sweety, "2) cutie: ", cutie);
console.log('');
console.log('---------------------------------------------');
console.log('');
var num1 = 100;
var num2 = 200;
var num3 = 300;

console.log("********** Before Swap *********");
console.log('');
console.log("num1: ", num1, " num2: ", num2, " num3: ", num3);
console.log('');
var temp = num1;
num1 = num2;
num2 = num3;
num3 = temp;
console.log("********** After Swap **********");
console.log('');
console.log("num1: ", num1, " num2: ", num2, " num3: ", num3);
console.log('');