//Variable declaration without Intialization value is undefined
var bankName;
console.log("*** Variable 'bankName' declaration without Intialization value ***");
console.log('Type of Variable - ',typeof bankName);
bankName ='SBI Bank';
console.log('');
console.log("*** Veriable Intialization ***");
console.log('Value of variable - ',bankName);
console.log("type of Variable - ", typeof bankName);
console.log('');
console.log("*** Variable 'Result' declaration with Intialization value 'null' ***");
var result = null;
console.log('Value of variable - ',result);
console.log("type of Variable - ", typeof result);
console.log('');
var mark ='90%';
console.log("*** Veriable Intialization ***");
console.log('Value of variable - ',mark);
console.log("type of Variable - ", typeof mark);
console.log('');
var isWorking = true;
console.log("*** Veriable Intialization ***");
console.log('Value of variable - ',isWorking);
console.log("type of Variable - ", typeof isWorking);
console.log('');
var totalCount = 'Hundred and seven';
console.log("*** Veriable Intialization ***");
console.log('Value of variable - ',totalCount);
console.log("type of Variable - ", typeof totalCount);
console.log('');
var totalCount = 107;
console.log("*** Veriable Intialization ***");
console.log('Value of variable - ',totalCount);
console.log("type of Variable - ", typeof totalCount);